FROM python:3.11-alpine

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apk add --no-cache git

WORKDIR /app

RUN git clone https://github.com/HamletDuFromage/vintelegram.git .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/data

VOLUME ["/app/data"]

CMD ["python", "bot.py"] 